---
- name: Copy desktop firewall rules
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/nftables/{{ item }}
    mode: u=rw,g=r,o=r
  with_items:
    - inet-in-kde.conf
    - inet-out-kde.conf
  notify: Validate and reload nftables firewall
