---
branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogTitle: '# Changelog'
  - - "@semantic-release/exec"
    - prepareCmd: "sed -i 's/^version: .*$/version: ${nextRelease.version}/' 'galaxy.yml'"
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      - galaxy.yml
  - "@semantic-release/github"
