---
- hosts: all
  roles:
    - role: xebis.ansible.grub
      vars:
        menu_timeout: 15
    - role: xebis.ansible.tmpfs
      vars:
        tmpfs_dirs:
          - /tmp
    - role: xebis.ansible.apt
      vars:
        autoclean: true
        autoremove: true
        cache_valid_time: 3600
        purge: true
        upgrade: "full"
    - role: xebis.ansible.nftables_firewall
      vars:
        nftables_firewall_log_rejected: true
    - role: xebis.ansible.openssh_server
    - role: xebis.ansible.fail2ban
    - role: xebis.ansible.users
      vars:
        passwordless_sudo: true
        ssh_password_login: false
        users:
          - user: mb
            admin: true
            ssh_keys_urls:
              - https://github.com/bruzina.keys
    - role: xebis.ansible.kde
    - role: xebis.ansible.google_chrome
    - role: xebis.ansible.obsidian
    - role: xebis.ansible.openssh_client
    - role: xebis.ansible.coding_projects
      vars:
        repositories:
          - owner: xebis
            name: .github
          - owner: xebis
            name: ansible-collection
          - owner: xebis
            name: github-actions-and-workflows
          - owner: xebis
            name: github-organization-as-code
          - owner: xebis
            name: hetzner-iac-cac
          - owner: xebis
            name: infra
    - role: xebis.ansible.visual_studio_code
