---
- hosts: all
  roles:
    - role: xebis.ansible.grub
      vars:
        menu_timeout: 15
    - role: xebis.ansible.apt
      vars:
        autoclean: true
        autoremove: true
        cache_valid_time: 3600
        purge: true
        upgrade: "full"
    - role: xebis.ansible.nftables_firewall
      vars:
        nftables_firewall_log_rejected: true
    - role: xebis.ansible.openssh_server
    - role: xebis.ansible.fail2ban
    - role: xebis.ansible.users
      vars:
        passwordless_sudo: true
        ssh_password_login: false
        users:
          - user: mb
            admin: true
            ssh_keys_urls:
              - https://github.com/bruzina.keys
