---
- name: Update and upgrade all deb packages
  become: true
  ansible.builtin.apt:
    cache_valid_time: "{{ cache_valid_time | default(omit) }}"
  notify: Upgrade deb packages

- name: Enforce upgrade and reboot now rather than at the end of the playbook
  ansible.builtin.meta: flush_handlers
