---
- name: Install direnv
  become: true
  ansible.builtin.apt:
    name:
      - direnv
    state: present

- name: Set up Bash to use direnv
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    block: |
      eval "$(direnv hook bash)"
    marker: "# {mark} direnv configuration"
    create: true
    mode: u=rw,g=,o=
