---
- name: Install direnv
  become: true
  ansible.builtin.apt:
    name:
      - direnv
    state: present

- name: Set up Bash to use direnv
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    block: |
      eval "$(direnv hook bash)"
    marker: "# {mark} direnv configuration"
    create: true
    mode: u=rw,g=,o=

- name: Create direnv configuration directory
  ansible.builtin.file:
    path: ~/.config/direnv
    state: directory
    mode: '0755'

- name: Copy direnv configuration
  ansible.builtin.copy:
    src: direnv.toml
    dest: ~/.config/direnv/direnv.toml
    mode: u=rw,g=,o=
