---
- name: Install Flatpak
  become: true
  ansible.builtin.apt:
    name:
      - flatpak
    state: present

- name: Upgrade global Flatpak packages
  become: true
  ansible.builtin.command:
    cmd: flatpak update --noninteractive
  register: flatpak_root_update
  changed_when: flatpak_root_update.stdout != "Nothing to do."

- name: Clean up global Flatpak
  become: true
  ansible.builtin.command:
    cmd: flatpak uninstall --unused --noninteractive
  register: flatpak_root_uninstall
  changed_when: flatpak_root_uninstall.stdout != "Nothing unused to uninstall"

- name: Upgrade user Flatpak packages
  ansible.builtin.command:
    cmd: flatpak update --noninteractive
  register: flatpak_user_update
  changed_when: flatpak_user_update.stdout != "Nothing to do."

- name: Clean up user Flatpak
  ansible.builtin.command:
    cmd: flatpak uninstall --unused --noninteractive
  register: flatpak_user_uninstall
  changed_when: flatpak_user_uninstall.stdout != "Nothing unused to uninstall"
