---
- name: Upgrade deb packages
  become: true
  ansible.builtin.apt:
    autoclean: "{{ autoclean | default(omit) }}"
    autoremove: "{{ autoremove | default(omit) }}"
    purge: "{{ purge | default(omit) }}"
    upgrade: "{{ upgrade | default(omit) }}"
  when: upgrade != "no"
  listen: Upgrade deb packages
  notify: Reboot system when required
