---
- name: Disable password SSH login
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^(#\s*)?PasswordAuthentication
    line: PasswordAuthentication no
  when: ssh_password_login | default(true)
  listen: Disable password SSH login
  notify: Restart ssh
