---
- name: Validate and reload all nftables firewall rules
  become: true
  ansible.builtin.command:
    cmd: nft -c -f /etc/nftables.conf
  changed_when: true
  listen: Validate and reload nftables firewall
  notify: Reload nftables firewall

- name: Reload all nftables firewall rules
  become: true
  ansible.builtin.command:
    cmd: /etc/nftables.conf
  changed_when: true
  listen: Reload nftables firewall
