---
- name: Add Microsoft apt signing key
  become: true
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Visual Studio Code apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    mode: u=rw,g=r,o=r
    state: present

- name: Install Visual Studio Code
  become: true
  ansible.builtin.apt:
    name: code
    state: latest
    update_cache: true

- name: Install Visual Studio Code extensions
  ansible.builtin.shell: code --list-extensions | grep "{{ item }}" || code --install-extension "{{ item }}"
  loop: "{{ extensions }}"
